[package]
name = "helium-sync-profile"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-restore = []

[dependencies]
directories.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
zip.workspace = true

[target.'cfg(windows)'.dependencies]
winreg = "0.55"

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
